
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: latest

- script: terraform version
  displayName: Verify Terraform Installation

- script: echo "Azure K8s Terraform!"
  displayName: Test

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa_key.pub'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)configuration/iaac/azure/kubernetes'
    backendServiceArm: 'Azure subscription 1(bb58363f-64e2-4c89-9fe0-18a66a90b86b)'
    backendAzureRmOverrideSubscriptionID: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendAzureRmResourceGroupName: 'rg-ado-k8s-iaac-pipeline'
    backendAzureRmStorageAccountName: 'adok8siaacpipeline'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'statefile.tfstate'